### ISSUE TITLE
selective tagging

### ISSUE THREAD

**Issue by JanKeesSchakel** [SensingClues/ontologies#5]
currently all texts of any document (including Cluey observations) are full scanned for concepts from all thesauri. This causes (at least) 2 problems:

1) if a project name includes the name of e.g. an animal (or a any other concept), the tagger includes that tag/concept to each observation. This pollutes  the statistics / counts of species. This issue is currently causing problems (see picture below).

2) all thesauri are used for all projects. That is problematic when a project requires a specific thesaurus. Currently not yet the case, but will become a problem when we grow bigger. 

Illustration issue 1 (vulture in project name and tagged, but not observed):
<img width="356" alt="Screen Shot 2021-05-09 at 10 36 08" src="https://user-images.githubusercontent.com/13226972/117565842-c07d3e00-b0b3-11eb-8afc-f20b5625c47f.png">

**Comment by JudithDekkers** [comment]
created issue #126 and #127 in the WITS project, as these are issues with different priorities and solutions
And because we are not allowed to use the word "project" anymore but use "group" instead ;)
